### ISSUE TITLE
Internet probably shouldn't translate as World Wide Web

### ISSUE THREAD

**Issue by battle1368** [Bark-fa/Anglish-Translator#10]
The World Wide Web is a separate concept/technology to the internet, so this is already a problematic translation. The net in internet, network, derives from net in the sense of a mesh, which is indeed Germanic, and work, also Germanic, so using net shouldn't be an issue. Inter- in this context suggests a connection between networks, rather than international, so we might use Between or Link. Alternatively, since the internet is a network of networks, we might use Over, as in Meta.

Thus, I would go with one of Linknet, Linkednet, Between-net, or Overnet. In my view, Overnet best captures the meaning of internet as a network of networks, while Linknet is a more direct translation.

By extension, a word for intranet could also be introduced, such as Within-net or Inside-net.

**Comment by Bark-fa** [comment]
edited
