### ISSUE TITLE
Why does the translator translate "us" as "brooing"?

### ISSUE THREAD

**Issue by Prometheus1962** [Bark-fa/Anglish-Translator#11]
The word "us" is Germanic in origin, being related to the German word "uns". I have no idea where "brooing" comes from, but it sounds really weird, especially when "us" works perfectly well as an Anglish word.

**Comment by Bark-fa** [comment]
PR Merged, sorry for taking so long but I rarely check this repo, I didn't even think anyone would ever see this :)
