### ISSUE TITLE
"Not" translates as "loing" - why not simply "not"?

### ISSUE THREAD

**Issue by Prometheus1962** [Bark-fa/Anglish-Translator#8]
From Online Etymology Dictionary:

not (adv.)
negative particle, a word expressing negation, denial, refusal, or prohibition, mid-13c., unstressed variant of noht, naht "in no way" (see [naught](https://www.etymonline.com/word/naught?ref=etymonline_crossreference))...
 compare Middle English not know an A from a windmill (c. 1400).

naught (n.)
(late 12c.), from Old English nawiht "nothing," literally "no whit," from na "no" (from PIE root *ne- "not") + wiht "thing, creature, being"

**Comment by Bark-fa** [comment]
The issue was caused by the grammar engine, specifically, the part that checks if the word is in present continuous, the function was not exiting upon detecting that the word is not even present continuous.
